/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import SendEmail.SendMail;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author devikamujgule
 */
public class SignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJpanel
     */
   

    JPanel mainWorkArea;
    EcoSystem system;
    String passregex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$";
    String emailregex ="^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
    Pattern pattern = Pattern.compile(passregex);
    Pattern patternemail = Pattern.compile(emailregex);
    public SignUpJPanel(JPanel mainWorkArea, EcoSystem system) {
        initComponents();
  
        this.system = system;
        System.out.println("system" + system); 
        this.mainWorkArea = mainWorkArea;
        System.out.println("inside signup form"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ImageHeader = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField_confirm = new javax.swing.JPasswordField();
        jPasswordField_main = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(110, 89, 222));

        Title.setFont(new java.awt.Font("STSong", 1, 62)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("ForYou");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ImageHeader)
                .addGap(20, 20, 20)
                .addComponent(Title)
                .addGap(0, 1275, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImageHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Title)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 110));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel7.setText("SIGN UP");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 112, 23));

        jLabel8.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel8.setText("Username:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 112, 23));
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 170, 40));

        jLabel9.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel9.setText("Email:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 72, 23));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 170, 40));

        jLabel10.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel10.setText("Password:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 112, 23));

        jLabel11.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel11.setText("Confirm Password:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 200, 23));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 220, 50));

        jPasswordField_confirm.setText("jPasswordField1");
        jPanel1.add(jPasswordField_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 170, 40));

        jPasswordField_main.setText("jPasswordField1");
        jPanel1.add(jPasswordField_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 170, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 560, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/mainimage.jpeg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public boolean isValid(String password) {
        Matcher matcher = pattern.matcher(password);
        return matcher.matches();
    }
    
    public boolean isValidEmail(String email) {
        Matcher matcher = patternemail.matcher(email);
        return matcher.matches();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String signup = "signup";
        if(!isValid(String.valueOf(jPasswordField_main.getPassword()))){
            JOptionPane.showMessageDialog(null, "Enter valid password with atleast on number, one lowercase letter, one uppercase letter,one special char and atleast 8 digits");
            
            return;
        }
        
        if(!isValidEmail(email.getText())){
            JOptionPane.showMessageDialog(null, "Enter valid Email ID");
            email.setText("");
            return;
        }
        
        if(system.checkIfUserIsUnique(Username.getText())){
        if(String.valueOf(jPasswordField_main.getPassword()).equals(String.valueOf(jPasswordField_confirm.getPassword()))){
            Employee employee1 = system.getEmployeeDirectory().createEmployee("customer");
            UserAccount ua1 = system.getUserAccountDirectory().createUserAccount(Username.getText(), String.valueOf(jPasswordField_main.getPassword()), employee1, new CustomerRole());
            ua1.getUserDetails().setEmailId(email.getText());
            System.out.println("customer list size>>"+system.getUserAccountDirectory().getUserAccountList().size());
            mainWorkArea.remove(this);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.previous(mainWorkArea);
           

        }else{
            JOptionPane.showMessageDialog(null, "Passwords do not match");
        }
        }else{
//            JOptionPane.showMessageDialog(null, "Enter unique username");
        }
         String abc = email.getText();
         SendMail email = new SendMail(abc,signup );
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageHeader;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField Username;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_confirm;
    private javax.swing.JPasswordField jPasswordField_main;
    // End of variables declaration//GEN-END:variables
}
