/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Customer;

import Business.EcoSystem;
import Business.Organizations.CovidCareOganization;
import Business.Organizations.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CovidCareWorkRequest;
import Business.WorkQueue.NursingWorkRequest;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author devikamujgule
 */
public class CovidCareServices extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    UserAccount userAccount;
    CovidCareOganization org;
    CovidCareWorkRequest request;

    /**
     * Creates new form CovidCareServices
     */
    public CovidCareServices(JPanel userProcessContainer, EcoSystem business, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = business;
        this.userAccount = userAccount;
        for (Organization organization : system.getNetwork().getEnterpriseDirectory().getEnterprise("Medical").getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof CovidCareOganization) {
                org = ((CovidCareOganization) organization);
                break;
            }
        }
        goWebsite(websiteText);
        showHideScheduleDoctorAppt(false);
        showHideVaccineBookingAppt(false);
    }

    public void showHideVaccineBookingAppt(Boolean value) {
        scheduleVaccineLabel.setVisible(value);
        scheduleVaccineTitle.setVisible(value);
        websiteText.setVisible(value);
    }

    public void showHideScheduleDoctorAppt(Boolean value) {
        schduleDoctorTitle.setVisible(value);
        dateLabel.setVisible(value);
        appointmentDateChooser.setVisible(value);
        doctorAppointmentBtn.setVisible(value);
    }

    private void goWebsite(JLabel website) {
        website.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new URI("https://www.vaccines.gov/search/?gclid=Cj0KCQiA2NaNBhDvARIsAEw55hhyC-Cn2PWVrKCFbxuyQxrplhwCkQcqbxZorOEGFnWWPJRM3Xs-bmwaApTvEALw_wcB"));
                } catch (URISyntaxException | IOException ex) {
                    //It looks like there's a problem
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSymptons = new javax.swing.ButtonGroup();
        buttonGroupContact = new javax.swing.ButtonGroup();
        buttonGroupVaccine = new javax.swing.ButtonGroup();
        HeaderPanel = new javax.swing.JPanel();
        ImageHeader1 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        vaccineTitle = new javax.swing.JLabel();
        symptonsLabel = new javax.swing.JLabel();
        yesRadioBtn = new javax.swing.JRadioButton();
        noRadioBtn = new javax.swing.JRadioButton();
        contactsLabel = new javax.swing.JLabel();
        contactYesRadioBtn = new javax.swing.JRadioButton();
        contactNoRadioBtn = new javax.swing.JRadioButton();
        wellNessSubmitBtn = new javax.swing.JButton();
        scheduleVaccineTitle = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        appointmentDateChooser = new com.toedter.calendar.JDateChooser();
        doctorAppointmentBtn = new javax.swing.JButton();
        wellNessCheckTitle = new javax.swing.JLabel();
        vaccineLabel = new javax.swing.JLabel();
        vaccineYesRadioBtn = new javax.swing.JRadioButton();
        vaccineNoRadioBtn = new javax.swing.JRadioButton();
        vaccineSubmitBtn = new javax.swing.JButton();
        schduleDoctorTitle = new javax.swing.JLabel();
        scheduleVaccineLabel = new javax.swing.JLabel();
        websiteText = new javax.swing.JLabel();
        serviceTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1254, 884));
        setSize(new java.awt.Dimension(1254, 884));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderPanel.setBackground(new java.awt.Color(110, 89, 222));

        Title1.setFont(new java.awt.Font("STSong", 1, 62)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setText("ForYou");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addComponent(ImageHeader1)
                .addGap(20, 20, 20)
                .addComponent(Title1)
                .addGap(0, 965, Short.MAX_VALUE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImageHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Title1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 110));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        vaccineTitle.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        vaccineTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vaccineTitle.setText("Vaccination");

        symptonsLabel.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        symptonsLabel.setText("Are you experiencing any symptons");

        buttonGroupSymptons.add(yesRadioBtn);
        yesRadioBtn.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        yesRadioBtn.setText("Yes");
        yesRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesRadioBtnActionPerformed(evt);
            }
        });

        buttonGroupSymptons.add(noRadioBtn);
        noRadioBtn.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        noRadioBtn.setText("No");

        contactsLabel.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        contactsLabel.setText("Have you been in contact with anyone having these symptons");

        buttonGroupContact.add(contactYesRadioBtn);
        contactYesRadioBtn.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        contactYesRadioBtn.setText("Yes");

        buttonGroupContact.add(contactNoRadioBtn);
        contactNoRadioBtn.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        contactNoRadioBtn.setText("No");

        wellNessSubmitBtn.setBackground(new java.awt.Color(0, 0, 0));
        wellNessSubmitBtn.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        wellNessSubmitBtn.setForeground(new java.awt.Color(255, 255, 255));
        wellNessSubmitBtn.setText("Submit");
        wellNessSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wellNessSubmitBtnActionPerformed(evt);
            }
        });

        scheduleVaccineTitle.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        scheduleVaccineTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scheduleVaccineTitle.setText("Schedule your covid vaccine");

        dateLabel.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        dateLabel.setText("Date");

        doctorAppointmentBtn.setBackground(new java.awt.Color(0, 0, 0));
        doctorAppointmentBtn.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        doctorAppointmentBtn.setForeground(new java.awt.Color(255, 255, 255));
        doctorAppointmentBtn.setText("Submit");
        doctorAppointmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorAppointmentBtnActionPerformed(evt);
            }
        });

        wellNessCheckTitle.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        wellNessCheckTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wellNessCheckTitle.setText("Wellness Check");

        vaccineLabel.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        vaccineLabel.setText("Have you been both taken covid-19 vaccination");

        buttonGroupVaccine.add(vaccineYesRadioBtn);
        vaccineYesRadioBtn.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        vaccineYesRadioBtn.setText("Yes");

        buttonGroupVaccine.add(vaccineNoRadioBtn);
        vaccineNoRadioBtn.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        vaccineNoRadioBtn.setText("No");

        vaccineSubmitBtn.setBackground(new java.awt.Color(0, 0, 0));
        vaccineSubmitBtn.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        vaccineSubmitBtn.setForeground(new java.awt.Color(255, 255, 255));
        vaccineSubmitBtn.setText("Submit");
        vaccineSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineSubmitBtnActionPerformed(evt);
            }
        });

        schduleDoctorTitle.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        schduleDoctorTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schduleDoctorTitle.setText("Kindly schedule an appointment with doctor");

        scheduleVaccineLabel.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        scheduleVaccineLabel.setText("Link to schedule your covid vaccination");

        websiteText.setBackground(new java.awt.Color(51, 51, 255));
        websiteText.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        websiteText.setForeground(new java.awt.Color(0, 51, 255));
        websiteText.setText("https://www.vaccines.gov/search/?gclid=Cj0KCQiA2NaNBhDvARIsAEw55hhyC-Cn2PWVrKCFbxuyQxrplhwCkQcqbxZorOEGFnWWPJRM3Xs-bmwaApTvEALw_wcB");

        serviceTitle.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        serviceTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serviceTitle.setText("Covid Care Services");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(symptonsLabel)
                            .addComponent(contactsLabel)
                            .addComponent(wellNessSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(contactYesRadioBtn)
                                .addGap(18, 18, 18)
                                .addComponent(contactNoRadioBtn))
                            .addComponent(vaccineSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(yesRadioBtn)
                                .addGap(18, 18, 18)
                                .addComponent(noRadioBtn)
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doctorAppointmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(appointmentDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(wellNessCheckTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(schduleDoctorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(vaccineLabel)
                        .addGap(47, 47, 47)
                        .addComponent(vaccineYesRadioBtn)
                        .addGap(18, 18, 18)
                        .addComponent(vaccineNoRadioBtn)
                        .addGap(37, 37, 37)
                        .addComponent(scheduleVaccineLabel)
                        .addGap(18, 18, 18)
                        .addComponent(websiteText)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serviceTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vaccineTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(scheduleVaccineTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {doctorAppointmentBtn, vaccineSubmitBtn, wellNessSubmitBtn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(serviceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wellNessCheckTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schduleDoctorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(symptonsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yesRadioBtn)
                        .addComponent(noRadioBtn)
                        .addComponent(dateLabel))
                    .addComponent(appointmentDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactYesRadioBtn)
                    .addComponent(contactNoRadioBtn))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wellNessSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorAppointmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vaccineTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduleVaccineTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vaccineLabel)
                    .addComponent(vaccineYesRadioBtn)
                    .addComponent(vaccineNoRadioBtn)
                    .addComponent(scheduleVaccineLabel)
                    .addComponent(websiteText))
                .addGap(18, 18, 18)
                .addComponent(vaccineSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {doctorAppointmentBtn, vaccineSubmitBtn, wellNessSubmitBtn});

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1180, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void yesRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesRadioBtnActionPerformed

    private void wellNessSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wellNessSubmitBtnActionPerformed
        // TODO add your handling code here:
        if (yesRadioBtn.isSelected() || noRadioBtn.isSelected() && (contactYesRadioBtn.isSelected() || contactNoRadioBtn.isSelected())) {
            request = new CovidCareWorkRequest();
            request.setIsHealthy(!yesRadioBtn.isSelected() || !contactYesRadioBtn.isSelected());
            if (yesRadioBtn.isSelected() || contactYesRadioBtn.isSelected()) {
                showHideScheduleDoctorAppt(true);
            } else {
                showHideScheduleDoctorAppt(false);
            }
            JOptionPane.showMessageDialog(this, "YOUR DAILY CHECK IS UPDATED");
            return;
        } else {
            JOptionPane.showMessageDialog(this, "SELECT OPTION BEFORE SUBMITTING");
        }
    }//GEN-LAST:event_wellNessSubmitBtnActionPerformed

    private void vaccineSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineSubmitBtnActionPerformed
        // TODO add your handling code here:
        if (vaccineYesRadioBtn.isSelected() || vaccineNoRadioBtn.isSelected()) {
            if (request == null) {
                request = new CovidCareWorkRequest();
            }
            request.setIsCovidVaccinated(vaccineYesRadioBtn.isSelected());
            if (vaccineYesRadioBtn.isSelected()) {
                showHideVaccineBookingAppt(false);
            } else {
                showHideVaccineBookingAppt(true);
            }
            JOptionPane.showMessageDialog(this, "YOUR VACCINE DETAILS ARE UPDATED");
            return;
        } else {
            JOptionPane.showMessageDialog(this, "SELECT OPTION BEFORE SUBMITTING");
        }

    }//GEN-LAST:event_vaccineSubmitBtnActionPerformed

    private void doctorAppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorAppointmentBtnActionPerformed
        // TODO add your handling code here:
        if (appointmentDateChooser.getDate() == null || appointmentDateChooser.getDate().before(new Date())) {
            JOptionPane.showMessageDialog(this, "SELECT A DATE AFTER TODAY");
            return;
        }
        request.setMessage("SCHEDULE DOCTOR APPOINTMENT PLEASE");
        request.setSender(userAccount);
        request.setAppointmentDate(appointmentDateChooser.getDate());
        request.setStatus("Sent");
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
//            request.setId(org.getWorkQueue().getWorkRequestList().size());
        }
        JOptionPane.showMessageDialog(this, "YOUR APPOINTMENT IS BOOKED !!");
    }//GEN-LAST:event_doctorAppointmentBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel ImageHeader1;
    private javax.swing.JLabel Title1;
    private com.toedter.calendar.JDateChooser appointmentDateChooser;
    private javax.swing.ButtonGroup buttonGroupContact;
    private javax.swing.ButtonGroup buttonGroupSymptons;
    private javax.swing.ButtonGroup buttonGroupVaccine;
    private javax.swing.JRadioButton contactNoRadioBtn;
    private javax.swing.JRadioButton contactYesRadioBtn;
    private javax.swing.JLabel contactsLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton doctorAppointmentBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton noRadioBtn;
    private javax.swing.JLabel schduleDoctorTitle;
    private javax.swing.JLabel scheduleVaccineLabel;
    private javax.swing.JLabel scheduleVaccineTitle;
    private javax.swing.JLabel serviceTitle;
    private javax.swing.JLabel symptonsLabel;
    private javax.swing.JLabel vaccineLabel;
    private javax.swing.JRadioButton vaccineNoRadioBtn;
    private javax.swing.JButton vaccineSubmitBtn;
    private javax.swing.JLabel vaccineTitle;
    private javax.swing.JRadioButton vaccineYesRadioBtn;
    private javax.swing.JLabel websiteText;
    private javax.swing.JLabel wellNessCheckTitle;
    private javax.swing.JButton wellNessSubmitBtn;
    private javax.swing.JRadioButton yesRadioBtn;
    // End of variables declaration//GEN-END:variables
}
