/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Customer;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Organizations.NursingOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import UI.LoginJPanel;
import UI.MainJFrame;

/**
 *
 * @author devikamujgule
 */
public class CustomerService extends javax.swing.JPanel {

    /**
     * Creates new form CustomerService
     */
    private String serviceName;
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public CustomerService(String orgName,JPanel 
            userProcessContainer, EcoSystem system, 
            UserAccount userAccount) {
        initComponents();
        this.setSize(1680, 1050);
        this.userAccount = userAccount;
        serviceName = orgName;
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        profileNameText.setText(userAccount.getEmployee().getName());
        if(serviceName != null) {
            switch(serviceName) {
                case "Nursing":
                    NursingServices nurse = new NursingServices(userProcessContainer,system, userAccount);
                    servicesSplitPane.setRightComponent(nurse);
                    NursingButton.setBorderPainted(true);
                    break;
                case "AllServices":
                    NewCustomerJPanel profile = new NewCustomerJPanel(userProcessContainer,system, userAccount);
                    servicesSplitPane.setRightComponent(profile);
                    ProfileButton.setBorderPainted(true);
                    break;
                case "Therapy":
                    TherapyServices therapy = new TherapyServices(userProcessContainer,system, userAccount);
                    servicesSplitPane.setRightComponent(therapy);
                    TherapyButton.setBorderPainted(true);
                    break;
                case "Meals":
                    OrderMeal meal = new OrderMeal(userProcessContainer, system, userAccount, servicesSplitPane);
                    servicesSplitPane.setRightComponent(meal);
                    MealDeliveryButton.setBorderPainted(true);
                    break;
                case "Legal":
                    ElderLawFirm lawfirm = new ElderLawFirm(userProcessContainer, system, userAccount, servicesSplitPane);
                    servicesSplitPane.setRightComponent(lawfirm);
                    LegalServicesButton.setBorderPainted(true);
                    break;
                default: break;
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        servicesSplitPane = new javax.swing.JSplitPane();
        ServicesPanel = new javax.swing.JPanel();
        ProfileButton = new javax.swing.JButton();
        NursingButton = new javax.swing.JButton();
        TherapyButton = new javax.swing.JButton();
        CovidCareButton = new javax.swing.JButton();
        MoneyManagementButton = new javax.swing.JButton();
        LegalServicesButton = new javax.swing.JButton();
        MealDeliveryButton = new javax.swing.JButton();
        GroceryDeliveryButton = new javax.swing.JButton();
        HouseHoldCareButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        profileIcon = new javax.swing.JLabel();
        profileNameText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CartBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        servicesSplitPane.setBorder(null);
        servicesSplitPane.setDividerSize(0);
        servicesSplitPane.setPreferredSize(new java.awt.Dimension(1480, 1000));

        ServicesPanel.setBackground(new java.awt.Color(54, 33, 89));

        ProfileButton.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        ProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        ProfileButton.setText("Profile");
        ProfileButton.setBorderPainted(false);
        ProfileButton.setContentAreaFilled(false);
        ProfileButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });

        NursingButton.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        NursingButton.setForeground(new java.awt.Color(255, 255, 255));
        NursingButton.setText("Nursing");
        NursingButton.setBorderPainted(false);
        NursingButton.setContentAreaFilled(false);
        NursingButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NursingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NursingButtonActionPerformed(evt);
            }
        });

        TherapyButton.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        TherapyButton.setForeground(new java.awt.Color(255, 255, 255));
        TherapyButton.setText("Therapy");
        TherapyButton.setBorderPainted(false);
        TherapyButton.setContentAreaFilled(false);
        TherapyButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TherapyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TherapyButtonActionPerformed(evt);
            }
        });

        CovidCareButton.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        CovidCareButton.setForeground(new java.awt.Color(255, 255, 255));
        CovidCareButton.setText("Covid Care");
        CovidCareButton.setBorderPainted(false);
        CovidCareButton.setContentAreaFilled(false);
        CovidCareButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CovidCareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CovidCareButtonActionPerformed(evt);
            }
        });

        MoneyManagementButton.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        MoneyManagementButton.setForeground(new java.awt.Color(255, 255, 255));
        MoneyManagementButton.setText("Funds");
        MoneyManagementButton.setBorderPainted(false);
        MoneyManagementButton.setContentAreaFilled(false);
        MoneyManagementButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MoneyManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyManagementButtonActionPerformed(evt);
            }
        });

        LegalServicesButton.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        LegalServicesButton.setForeground(new java.awt.Color(255, 255, 255));
        LegalServicesButton.setText("Legal");
        LegalServicesButton.setBorderPainted(false);
        LegalServicesButton.setContentAreaFilled(false);
        LegalServicesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LegalServicesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LegalServicesButtonActionPerformed(evt);
            }
        });

        MealDeliveryButton.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        MealDeliveryButton.setForeground(new java.awt.Color(255, 255, 255));
        MealDeliveryButton.setText("Meals");
        MealDeliveryButton.setBorderPainted(false);
        MealDeliveryButton.setContentAreaFilled(false);
        MealDeliveryButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MealDeliveryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealDeliveryButtonActionPerformed(evt);
            }
        });

        GroceryDeliveryButton.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        GroceryDeliveryButton.setForeground(new java.awt.Color(255, 255, 255));
        GroceryDeliveryButton.setText("Grocery");
        GroceryDeliveryButton.setBorderPainted(false);
        GroceryDeliveryButton.setContentAreaFilled(false);
        GroceryDeliveryButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GroceryDeliveryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroceryDeliveryButtonActionPerformed(evt);
            }
        });

        HouseHoldCareButton.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        HouseHoldCareButton.setForeground(new java.awt.Color(255, 255, 255));
        HouseHoldCareButton.setText("Household Chore");
        HouseHoldCareButton.setBorderPainted(false);
        HouseHoldCareButton.setContentAreaFilled(false);
        HouseHoldCareButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HouseHoldCareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HouseHoldCareButtonActionPerformed(evt);
            }
        });

        HomeButton.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(255, 255, 255));
        HomeButton.setText("Home");
        HomeButton.setBorderPainted(false);
        HomeButton.setContentAreaFilled(false);
        HomeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HomeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/usericon.png"))); // NOI18N

        profileNameText.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        profileNameText.setForeground(new java.awt.Color(255, 255, 255));

        CartBtn.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        CartBtn.setForeground(new java.awt.Color(255, 255, 255));
        CartBtn.setText("Cart");
        CartBtn.setBorderPainted(false);
        CartBtn.setContentAreaFilled(false);
        CartBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ServicesPanelLayout = new javax.swing.GroupLayout(ServicesPanel);
        ServicesPanel.setLayout(ServicesPanelLayout);
        ServicesPanelLayout.setHorizontalGroup(
            ServicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NursingButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CovidCareButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TherapyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MoneyManagementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LegalServicesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GroceryDeliveryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MealDeliveryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HouseHoldCareButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ProfileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(CartBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ServicesPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(ServicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(profileIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ServicesPanelLayout.setVerticalGroup(
            ServicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicesPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(profileIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfileButton)
                .addGap(0, 0, 0)
                .addComponent(CartBtn)
                .addGap(0, 0, 0)
                .addComponent(NursingButton)
                .addGap(0, 0, 0)
                .addComponent(CovidCareButton)
                .addGap(0, 0, 0)
                .addComponent(TherapyButton)
                .addGap(0, 0, 0)
                .addComponent(MoneyManagementButton)
                .addGap(0, 0, 0)
                .addComponent(LegalServicesButton)
                .addGap(0, 0, 0)
                .addComponent(GroceryDeliveryButton)
                .addGap(0, 0, 0)
                .addComponent(MealDeliveryButton)
                .addGap(0, 0, 0)
                .addComponent(HouseHoldCareButton)
                .addGap(0, 0, 0)
                .addComponent(HomeButton)
                .addGap(0, 0, 0)
                .addComponent(logoutButton)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        servicesSplitPane.setLeftComponent(ServicesPanel);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1254, 1000));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        servicesSplitPane.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(servicesSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(servicesSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButtonActionPerformed
        // TODO add your handling code here:
        NewCustomerJPanel profile = new NewCustomerJPanel(userProcessContainer, system, userAccount);
        servicesSplitPane.setRightComponent(profile);
    }//GEN-LAST:event_ProfileButtonActionPerformed

    private void NursingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NursingButtonActionPerformed
        // TODO add your handling code here:
        NursingServices nurse = new NursingServices(userProcessContainer,system, userAccount);
        servicesSplitPane.setRightComponent(nurse);
    }//GEN-LAST:event_NursingButtonActionPerformed

    private void TherapyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TherapyButtonActionPerformed
        // TODO add your handling code here:
        TherapyServices therapy = new TherapyServices(userProcessContainer,system, userAccount);
        servicesSplitPane.setRightComponent(therapy);
    }//GEN-LAST:event_TherapyButtonActionPerformed

    private void CovidCareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CovidCareButtonActionPerformed
        // TODO add your handling code here:
        CovidCareServices care = new CovidCareServices(userProcessContainer,system, userAccount);
        servicesSplitPane.setRightComponent(care);
    }//GEN-LAST:event_CovidCareButtonActionPerformed

    private void MoneyManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoneyManagementButtonActionPerformed
        // TODO add your handling code here:
        MoneyManagement money = new MoneyManagement(userProcessContainer,system,userAccount,servicesSplitPane);
        servicesSplitPane.setRightComponent(money);
    }//GEN-LAST:event_MoneyManagementButtonActionPerformed

    private void LegalServicesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LegalServicesButtonActionPerformed
        // TODO add your handling code here:
        ElderLawFirm law = new ElderLawFirm(userProcessContainer, system, userAccount, servicesSplitPane);
       servicesSplitPane.setRightComponent(law);
    }//GEN-LAST:event_LegalServicesButtonActionPerformed

    private void MealDeliveryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealDeliveryButtonActionPerformed
        // TODO add your handling code here:
        OrderMeal profile = new OrderMeal(userProcessContainer, system, userAccount, servicesSplitPane);
        servicesSplitPane.setRightComponent(profile);
    }//GEN-LAST:event_MealDeliveryButtonActionPerformed

    private void GroceryDeliveryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroceryDeliveryButtonActionPerformed
        // TODO add your handling code here:
        GroceryAndEssentialsJPanel grocery = new GroceryAndEssentialsJPanel(userProcessContainer, system, userAccount, servicesSplitPane);
        servicesSplitPane.setRightComponent(grocery);
    }//GEN-LAST:event_GroceryDeliveryButtonActionPerformed

    private void HouseHoldCareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HouseHoldCareButtonActionPerformed
        // TODO add your handling code here:
        HouseHoldChoreServices choreServices = new HouseHoldChoreServices(userProcessContainer, system, userAccount, servicesSplitPane);
        servicesSplitPane.setRightComponent(choreServices);
    }//GEN-LAST:event_HouseHoldCareButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.removeAll();
        dB4OUtil.storeSystem(system);
        EcoSystem system1 = dB4OUtil.retrieveSystem();
        JPanel loginPage = new LoginJPanel(userProcessContainer, system1);
        userProcessContainer.add("loginPage",loginPage);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void CartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartBtnActionPerformed
        // TODO add your handling code here:
        ServiceCart cart = new ServiceCart(userProcessContainer, system, userAccount,servicesSplitPane);
        servicesSplitPane.setRightComponent(cart);
    }//GEN-LAST:event_CartBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CartBtn;
    private javax.swing.JButton CovidCareButton;
    private javax.swing.JButton GroceryDeliveryButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton HouseHoldCareButton;
    private javax.swing.JButton LegalServicesButton;
    private javax.swing.JButton MealDeliveryButton;
    private javax.swing.JButton MoneyManagementButton;
    private javax.swing.JButton NursingButton;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JPanel ServicesPanel;
    private javax.swing.JButton TherapyButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JLabel profileNameText;
    private javax.swing.JSplitPane servicesSplitPane;
    // End of variables declaration//GEN-END:variables
}
