/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Customer;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author devikamujgule
 */
public class PaymentJpanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentJpanel
     */
    private UserAccount useraccount;
    private Double price;
    private JSplitPane servicesSplitPane;
    private JPanel userProcessContainer;
    private EcoSystem system;
    
    public PaymentJpanel(UserAccount useraccount, Double price) {
        initComponents();
        this.useraccount = useraccount;
        this.price = price;
        this.userProcessContainer = userProcessContainer;
        this.servicesSplitPane = servicesSplitPane;
        this.system = system;
        jTextField_totalCost.setText(price.toString());
        System.out.println("check details...."+useraccount.getCardDetails().getCardHolderName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        ImageHeader = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_totalCost = new javax.swing.JTextField();
        jButton_Payment = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1254, 1000));

        jPanelHeader.setBackground(new java.awt.Color(110, 89, 222));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(1254, 116));
        jPanelHeader.setSize(new java.awt.Dimension(1254, 116));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelHeader.add(ImageHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 110));

        Title.setFont(new java.awt.Font("STSong", 1, 62)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("ForYou");
        jPanelHeader.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setSize(new java.awt.Dimension(1254, 884));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        jLabel1.setText("Payment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel2.setText("Subtotal :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));

        jTextField_totalCost.setEditable(false);
        jPanel1.add(jTextField_totalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 155, 34));

        jButton_Payment.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Payment.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jButton_Payment.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Payment.setText("Pay from Wallet");
        jButton_Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PaymentActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 279, 45));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/paymentbkg.png"))); // NOI18N
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PaymentActionPerformed
        // TODO add your handling code here:
        if(useraccount.getCardDetails() != null){
            Double balance = useraccount.getCardDetails().getBalance();
        if(balance >= price){
        balance = balance - price;
        useraccount.getCardDetails().setBalance(balance);
        System.out.println("balance....."+useraccount.getCardDetails().getBalance());
        jTextField_totalCost.setText("");
        JOptionPane.showMessageDialog(null, "Payment Successful");
        }else{
            JOptionPane.showMessageDialog(null, "Insufficient Balance");
        }
        }else{
            JOptionPane.showMessageDialog(null, "Card details not added");
        }
        
    }//GEN-LAST:event_jButton_PaymentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageHeader;
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButton_Payment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JTextField jTextField_totalCost;
    // End of variables declaration//GEN-END:variables
}
