/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin.HomeEssentials;

import UI.Admin.Food.*;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author devikamujgule
 */
public class AdminProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminProfileJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    UserAccount userAccount;
    JSplitPane adminSplitPane;
    
        
    public AdminProfileJPanel(JPanel userProcessContainer, 
            UserAccount userAccount, 
            EcoSystem system, 
            JSplitPane adminSplitPane) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        
            addItemToComboBoxList();
            displayDetails();
        
        
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel3 = new javax.swing.JPanel();
        ImageHeader4 = new javax.swing.JLabel();
        Title4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        custIdTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        custNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AddressStreetTextField = new javax.swing.JTextField();
        AddressAptTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        ZipcodejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PhoneNumberTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emailAddressTextField1 = new javax.swing.JTextField();
        SubmitjButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        emergencyNameTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        emergencyNumberTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        ageTextField = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderPanel3.setBackground(new java.awt.Color(110, 89, 222));
        HeaderPanel3.setPreferredSize(new java.awt.Dimension(1254, 116));

        Title4.setFont(new java.awt.Font("STSong", 1, 62)); // NOI18N
        Title4.setForeground(new java.awt.Color(255, 255, 255));
        Title4.setText("ForYou");

        javax.swing.GroupLayout HeaderPanel3Layout = new javax.swing.GroupLayout(HeaderPanel3);
        HeaderPanel3.setLayout(HeaderPanel3Layout);
        HeaderPanel3Layout.setHorizontalGroup(
            HeaderPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanel3Layout.createSequentialGroup()
                .addComponent(ImageHeader4)
                .addGap(20, 20, 20)
                .addComponent(Title4)
                .addGap(0, 912, Short.MAX_VALUE))
        );
        HeaderPanel3Layout.setVerticalGroup(
            HeaderPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanel3Layout.createSequentialGroup()
                .addGroup(HeaderPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImageHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Title4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(HeaderPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1127, -1));

        jLabel2.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        jLabel2.setText("Admin Id:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 208, 130, 23));
        add(custIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 207, 165, -1));

        jLabel3.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        jLabel3.setText("Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 246, 90, 23));
        add(custNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 245, 165, -1));

        jLabel4.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        jLabel4.setText("Age:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 321, 90, 23));

        jLabel5.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        jLabel5.setText("Address:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 208, 90, 23));
        add(AddressStreetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 207, 165, -1));
        add(AddressAptTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 239, 165, -1));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 271, 165, -1));
        add(ZipcodejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 304, 165, -1));

        jLabel6.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        jLabel6.setText("Phone Number:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 337, 130, 23));

        PhoneNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PhoneNumberTextFieldKeyReleased(evt);
            }
        });
        add(PhoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 336, 165, -1));

        jLabel7.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        jLabel7.setText("Date of Birth:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, 23));

        jLabel8.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        jLabel8.setText("Email Address:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 381, 130, 23));
        add(emailAddressTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 165, -1));

        SubmitjButton.setBackground(new java.awt.Color(0, 0, 0));
        SubmitjButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitjButton.setText("Submit");
        SubmitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitjButtonActionPerformed(evt);
            }
        });
        add(SubmitjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 559, 150, 40));

        jLabel11.setFont(new java.awt.Font("STSong", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Personal Details");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 122, 1127, 67));

        jLabel12.setFont(new java.awt.Font("STSong", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Emergency Contact Details");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 424, 1127, 32));

        jLabel13.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        jLabel13.setText("Name:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 459, 72, 23));
        add(emergencyNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 458, 165, -1));

        jLabel14.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        jLabel14.setText("Phone Number:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 500, 123, -1));

        emergencyNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emergencyNumberTextFieldKeyReleased(evt);
            }
        });
        add(emergencyNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 496, 165, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 412, 1121, 6));

        ageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ageTextFieldKeyReleased(evt);
            }
        });
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 321, 165, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 277, 165, -1));
        add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 160, 30));

        l3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                l3KeyReleased(evt);
            }
        });
        add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 170, 30));

        l2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                l2KeyReleased(evt);
            }
        });
        add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 336, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitjButtonActionPerformed
        // TODO add your handling code here:
         boolean flag = false;
        List<UserAccount> userList = system.getUserAccountDirectory().getUserAccountList();

        for(int i = 0; i < userList.size(); i++){
            if(userList.get(i).getUsername().equals(userAccount.getUsername())){
                flag = true;
                userList.get(i).getUserDetails().setCustomerId(Integer.parseInt(custIdTextField.getText()));
                userList.get(i).getUserDetails().setName(custNameTextField.getText());
                userList.get(i).getUserDetails().setDob(jDateChooser1.getDate());
                userList.get(i).getUserDetails().setAge(Integer.parseInt(ageTextField.getText()));
                userList.get(i).getUserDetails().setAddressStreet(AddressStreetTextField.getText());
                userList.get(i).getUserDetails().setAddressApt(AddressAptTextField.getText());
                userList.get(i).getUserDetails().setAddressState(jComboBox1.getSelectedItem().toString());
                userList.get(i).getUserDetails().setAddressZipcode(ZipcodejTextField.getText());
                userList.get(i).getUserDetails().setPhoneNumber(Integer.parseInt(PhoneNumberTextField.getText()));
                userList.get(i).getUserDetails().setEmailId(emailAddressTextField1.getText());
                userList.get(i).getUserDetails().setEmergencyContactName(emergencyNameTextField1.getText());
                userList.get(i).getUserDetails().setEmemergencyContactNumber(Integer.parseInt(emergencyNumberTextField.getText()));
            }
        }
    }//GEN-LAST:event_SubmitjButtonActionPerformed

    private void ageTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextFieldKeyReleased
        // TODO add your handling code here:
        
        String regex = "^[0-9]{1,2}$";
        
        Pattern patt = Pattern.compile(regex);

        Matcher match = patt.matcher(ageTextField.getText());

        if(!match.matches()){

            l1.setText("ENTER AN APT AGE");

        }
        else{

            l1.setText(null);
        }
    }//GEN-LAST:event_ageTextFieldKeyReleased

    private void l2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_l2KeyReleased
        // TODO add your handling code here:
        
//        String regex = "^[0-9]{10}$";
//        
//        Pattern patt = Pattern.compile(regex);
//       
//
//        Matcher match = patt.matcher(PhoneNumberTextField.getText());
//        
//        if(!match.matches()){
//        
//            l2.setText("Incorrect Format");
//        
//        }
//        else{
//            
//            l2.setText(null);
//        }
    }//GEN-LAST:event_l2KeyReleased

    private void l3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_l3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_l3KeyReleased

    private void emergencyNumberTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emergencyNumberTextFieldKeyReleased
        // TODO add your handling code here:
        
        String regex = "^[0-9]{10}$";
        
        Pattern patt = Pattern.compile(regex);
       

        Matcher match = patt.matcher(emergencyNumberTextField.getText());
        
        if(!match.matches()){
        
            l3.setText("ENTER A 10 DIGIT PHONE NUMBER");
        
        }
        else{
            
            l3.setText(null);
        }
    }//GEN-LAST:event_emergencyNumberTextFieldKeyReleased

    private void PhoneNumberTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneNumberTextFieldKeyReleased
        // TODO add your handling code here:
        
        String regex = "^[0-9]{10}$";
//        
        Pattern patt = Pattern.compile(regex);
       

        Matcher match = patt.matcher(PhoneNumberTextField.getText());
        
        if(!match.matches()){
        
            l2.setText("ENTER A 10 DIGIT PHONE NUMBER");
        
        }
        else{
            
            l2.setText(null);
        }
    }//GEN-LAST:event_PhoneNumberTextFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressAptTextField;
    private javax.swing.JTextField AddressStreetTextField;
    private javax.swing.JPanel HeaderPanel3;
    private javax.swing.JLabel ImageHeader4;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JButton SubmitjButton;
    private javax.swing.JLabel Title4;
    private javax.swing.JTextField ZipcodejTextField;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField custIdTextField;
    private javax.swing.JTextField custNameTextField;
    private javax.swing.JTextField emailAddressTextField1;
    private javax.swing.JTextField emergencyNameTextField1;
    private javax.swing.JTextField emergencyNumberTextField;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    // End of variables declaration//GEN-END:variables

    private void addItemToComboBoxList() {
         jComboBox1.addItem("Arizona");
        jComboBox1.addItem("California");
        jComboBox1.addItem("Connecticut");
        jComboBox1.addItem("Florida");
        jComboBox1.addItem("Georgia");
        jComboBox1.addItem("Indiana");
        jComboBox1.addItem("Maryland");
        jComboBox1.addItem("Massachusetts");
        jComboBox1.addItem("Michigan");
        jComboBox1.addItem("New Jersey");
        jComboBox1.addItem("New York");
        jComboBox1.addItem("Texas");
        jComboBox1.addItem("Washington");
    }
    
     private void displayDetails() {
     if(userAccount.getUserDetails() == null){
            System.out.println("details if>>>");
            custIdTextField.setText("");
            custNameTextField.setText("");
            ageTextField.setText("");
            AddressStreetTextField.setText("");
            AddressAptTextField.setText("");
            jComboBox1.setSelectedItem("None");
            ZipcodejTextField.setText("");
            PhoneNumberTextField.setText("");
            emailAddressTextField1.setText("");
            emergencyNameTextField1.setText("");
            emergencyNumberTextField.setText("");
        }
else{
            System.out.println("details if>>>");
            custIdTextField.setText(String.valueOf(userAccount.getUserDetails().getCustomerId()));
            custNameTextField.setText(userAccount.getUserDetails().getName());
            jDateChooser1.setDate(userAccount.getUserDetails().getDob());
            ageTextField.setText(String.valueOf(userAccount.getUserDetails().getAge()));
            AddressStreetTextField.setText(userAccount.getUserDetails().getAddressStreet());
            AddressAptTextField.setText(userAccount.getUserDetails().getAddressApt());
            jComboBox1.setSelectedItem(userAccount.getUserDetails().getAddressState());
            ZipcodejTextField.setText(userAccount.getUserDetails().getAddressZipcode());
            PhoneNumberTextField.setText(String.valueOf(userAccount.getUserDetails().getPhoneNumber()));
            emailAddressTextField1.setText(userAccount.getUserDetails().getEmailId());
            emergencyNameTextField1.setText(userAccount.getUserDetails().getEmergencyContactName());
            emergencyNumberTextField.setText(String.valueOf(userAccount.getUserDetails().getEmemergencyContactNumber()));
        }
    }
}
